Book/Book/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin

urlpatterns = [

    path('xadmin/', xadmin.site.urls), #后台
    path('tinymce/',include('tinymce.urls')),
    path('user/',include('users.urls',namespace='user')),#用户模块
    path('cart/',include('cart.urls',namespace='cart')), #购物车模块
    path('order/',include('order.urls',namespace='order')),
    path('comment/',include('comments.urls',namespace='comment')),#评论模块
    path('search/',include('haystack.urls')),
    path('',include('books.urls',namespace='books')),


]

Book/books/urls.py
from django.urls import path,include
from . import views
app_name='books'

urlpatterns =[
    path('books/<int:books_id>/',views.detail,name='detail'),
    path('list/<int:type_id>/<int:page>/',views.list,name='list'),
    path('',views.index,name='index'), #首页
    path('collection/',views.Collection.as_view(),name='collection'),#书籍采集
    path('modify/',views.Modify.as_view(),name='modify')#书籍修改

]

Book/order/urls.py
from django.urls import path
from order import views
app_name='order'

urlpatterns=[
    path('place/',views.order_place,name='place'),#订单提交页面
    path('commit/',views.order_commit,name='commit'), #生成订单
    path('pay/',views.order_pay,name='pay'),
    path('check_pay/',views.check_pay,name='check_pay'),
]

Book/users/urls.py
from django.urls import path,re_path
from . import views
app_name='user'

urlpatterns =[
    path('register/',views.Register.as_view(),name='register'),#用户注册
    re_path(r'^active/(?P<token>.*)/$', views.register_active, name='active'),#邮箱激活

    path('login/',views.Login.as_view(),name='login'),#登录
    path('verifycode/',views.verifycode,name='verifycode'),#验证码
    path('logout/',views.logout,name='logout'),#退出

    re_path(r'^order/(?P<page>\d+)?/?$',views.order,name='order'),#订单
    path('address/', views.address, name='address'),#收货地址
    path('default_address/',views.default_address,name='default_address'),
    path('delete_address/',views.delete_address,name='delete_address'),
    path('test/',views.SqlTest.as_view(),name='test'),#sql注入演示
    path('',views.user,name='user'), #用户中心
]

Book/users/models.py
'''
用户信息模型
'''


from django.db import models
from db.base_model import BaseModel
from django.contrib.auth.hashers import make_password

# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self, username, password, email):
        '''添加一个账户信息'''
        passport = self.create(username=username, password=password, email=email)
        # 3.返回passport
        return passport

    def get_one_passport(self, username, password):
        '''根据用户名密码查找账户的信息'''
        try:
            passport = self.get(username=username, password=password,is_delete=False,is_active=True)
        except self.model.DoesNotExist:
            # 账户不存在
            passport = None
        return passport

class Passport(BaseModel):
    '''用户模型类'''
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')
    # 用户表的管理器
    objects = PassportManager()
    #模型元数据
    class Meta:
        #在后台管理中的名字
        verbose_name_plural = verbose_name = '账户管理'

    def __str__(self):
        return self.username


class AddressManager(models.Manager):
    '''地址模型管理器类'''
    def get_default_address(self, passport_id):
        '''查询指定用户的默认收货地址'''
        try:
            addr = self.filter(passport_id=passport_id, is_default=True).get(is_delete=False)
        except self.model.DoesNotExist:
            # 没有默认收货地址
            addr = None
        return addr

    def add_one_address(self, passport_id, recipient_name, recipient_addr, zip_code, recipient_phone):
        '''添加收货地址'''
        # 判断用户是否有默认收货地址
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            # 存在默认地址
            is_default = False
        else:
            # 不存在默认地址
            is_default = True

        # 添加一个地址
        addr = self.create(passport_id=passport_id,
                           recipient_name=recipient_name,
                           recipient_addr=recipient_addr,
                           zip_code=zip_code,
                           recipient_phone=recipient_phone,
                           is_default=is_default)
        return addr

class Address(BaseModel):
    '''地址模型类'''
    recipient_name = models.CharField(max_length=20, verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    passport = models.ForeignKey('Passport', verbose_name='账户',on_delete=models.CASCADE)#级联删除

    objects = AddressManager()

    class Meta:
        verbose_name_plural = verbose_name = '地址管理'

    def __str__(self):
        return self.recipient_addr

Book/users/views.py
import re

from django.core.paginator import Paginator
from django.http import JsonResponse
import redis
from django_redis import get_redis_connection
from django.shortcuts import render, redirect, reverse
from django.views import View
from itsdangerous import SignatureExpired
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from utils.utils import login_required
from .tasks import send_active_email
from users.models import Passport,Address
from users.models import *
from books.models import *
from cart.models import *
from order.models import *
from django.views.decorators.cache import cache_page
# Create your views here.

#注册,需要验证邮箱
class Register(View):
    def get(self,request):
        return render(request, 'users/register.html')
    '''进行用户注册处理'''
    def post(self,request):
        #接收post过来的数据
        username=request.POST.get('user_name')
        password=request.POST.get('pwd')
        email=request.POST.get('email')

        #进行数据校验
        if not all([username,password,email]):
            #有数据为空
            return render(request,'users/register.html',context={'errmsg':'参数不能为空'})
        if not re.match(r'^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$', email):
            #邮箱不合法
            return render(request, 'users/register.html', {'errmsg': '邮箱不合法!'})
        # 注册，向数据库中添加账户
        try:
            passport=Passport.objects.add_one_passport(username=username,password=password,email=email)
        except Exception as e:
            print('error:',e)
            return render(request,'users/register.html',{'errmsg':'用户名已存在！'})

        serializer = Serializer(settings.SECRET_KEY, 3600)
        token = serializer.dumps({'confirm': passport.id})  # 返回bytes
        token = token.decode()
        #发送激活邮箱
        send_active_email.delay(token, email)
        passport.save()

        # 注册完，还是返回注册页。
        # return redirect(reverse('user:register'))
        return HttpResponse("注册成功！请检查邮箱以激活您的账户！")

#邮箱验证
def register_active(request, token):
    '''用户账户激活'''
    serializer = Serializer(settings.SECRET_KEY, 3600)
    try:
        info = serializer.loads(token)
        passport_id = info['confirm']
        # 进行用户激活
        passport = Passport.objects.get(id=passport_id)
        passport.is_active = True
        passport.save()
        # 跳转的登录页
        return redirect(reverse('user:login'))
    except SignatureExpired:
        # 链接过期
        return HttpResponse('激活链接已过期')

#登录
class Login(View):
    #请求登录页面
    def get(self,request):
        #用cookie自动填用户名和密码
        if request.COOKIES.get('username'):
            username=request.COOKIES.get('username')
            checked='checked'
        else:
            username=''
            checked=''
        if request.COOKIES.get('password'):
            password=request.COOKIES.get('password')
        else:
            password=''
        context={
            'username':username,
            'password':password,
            'checked':checked,
        }
        return render(request,'users/login.html',context=context)

    #提交登录请求
    def post(self,request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember = request.POST.get('remember')
        verifycode = request.POST.get('verifycode')
        # 数据校验
        if not all([username, password]):
            # 有数据为空
            return JsonResponse({'res': 0})
        #验证码是否正确
        if verifycode.upper() != request.session['verifycode']:
            return JsonResponse({'res': 1})
        # 数据库中查找账户信息
        passport = Passport.objects.get_one_passport(username=username, password=password)
        #验证通过,跳转到首页
        if passport:
            #反转函数，即通过视图反转得到url
            next_url=reverse('books:index')
            print(next_url)
            #需要返回的JsonResponse对象，是HttpResponse的子类
            jres=JsonResponse({'res':2,'next_url':next_url})

            #判断是否需要记住用户名和密码
            #json传递过来的都是字符串，
            if remember=='true':
                #调用HttpResponse对象的方法设置cookie
                jres.set_cookie('username',username,max_age=7*24*3600)
                jres.set_cookie('password',password,max_age=7*24*3600)
            else:
                #不记住用户名和密码
                jres.delete_cookie('username')
                jres.delete_cookie('password')
            #设置会话，记住用户的登录状态
            request.session['islogin']=True
            request.session['username']=username
            request.session['passport_id']=passport.id
            #登录成功后清理图片缓存
            del request.session['verifycode']
            return jres

        else:
            #用户名或密码错误
            return JsonResponse({'res':0})


#图片验证码
from django.http import HttpResponse
from django.conf import settings
import os
from PIL import Image,ImageDraw,ImageFont
import random
def verifycode(request):
    #背景色
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    #宽高
    width=100
    height=25
    size=(width,height)
    #创建画面对象
    im=Image.new('RGB',size,bgcolor)
    #创建画笔对象
    draw=ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in  range(0,100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype(os.path.join(settings.BASE_DIR, "ALGER.TTF"), 15)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw

    #将验证码存入session
    request.session['verifycode']=rand_str

    import io
    buf=io.BytesIO()
    im.save(buf,'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


#用户订单
@login_required
def order(request, page):
    '''用户中心-订单页'''
    # 查询用户的订单信息
    passport_id = request.session.get('passport_id')

    # 获取用户的所有订单信息
    order_li = OrderInfo.objects.filter(passport_id=passport_id)

    # 遍历获取订单的商品信息
    # order->OrderInfo实例对象
    for order in order_li:
        # 根据订单id查询订单商品信息
        order_id = order.order_id
        order_books_li = OrderBooks.objects.filter(order_id=order_id)

        # 计算商品的小计
        # order_books ->OrderGoods实例对象
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            amount = count * price
            # 保存订单中每一个商品的小计
            order_books.amount = amount

        # 给order对象动态增加一个属性order_books_li,保存订单中商品的信息
        order.order_books_li = order_books_li

    paginator = Paginator(order_li, 3)  # 每页显示3个订单

    num_pages = paginator.num_pages

    if not page:  # 首次进入时默认进入第一页
        page = 1
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)

    order_li = paginator.page(page)

    if num_pages < 5:
        pages = range(1, num_pages + 1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages - 4, num_pages + 1)
    else:
        pages = range(page - 2, page + 3)

    context = {
        'order_li': order_li,
        'pages': pages,
    }

    return render(request, 'users/user_center_order.html', context)


#用户中心,要判断用户是否登录，没有登录则跳转到登录界面，这里用装饰器
@login_required
def user(request):
    '''用户中心-信息页'''
    passport_id = request.session.get('passport_id')
    # 获取用户的基本信息
    addr = Address.objects.get_default_address(passport_id=passport_id)

    # 获取用户的最近浏览信息
    con = get_redis_connection('default')
    key = 'history_%d' % passport_id
    # 取出用户最近浏览的5个商品的id
    history_li = con.lrange(key, 0, 4)
    # history_li = [21,20,11]
    # print(history_li)
    # 查询数据库,获取用户最近浏览的商品信息
    # books_li = Books.objects.filter(id__in=history_li)
    books_li = []
    for id in history_li:
        books = Books.objects.get_books_by_id(books_id=id)
        books_li.append(books)

    return render(request, 'users/user_center_info.html', {'addr': addr,
                                                           'page': 'user',
                                                           'books_li': books_li})




#退出
def logout(request):
    # 清空用户的session信息
    request.session.flush()
    # 跳转到首页
    return redirect(reverse('books:index'))

@login_required
def address(request):
    '''用户中心-地址页'''
    # 获取登录用户的id
    passport_id = request.session.get('passport_id')

    if request.method == 'GET':
        # 显示地址页面
        # 查询用户的默认地址
        addr = Address.objects.get_default_address(passport_id=passport_id)
        #查询用户的所有地址,是一个列表
        addrs=Address.objects.filter(passport_id=passport_id).filter(is_delete=False)

        return render(request, 'users/user_center_site.html', {'addr': addr, 'addrs': addrs})
    else:
        # 添加收货地址
        # 1.接收数据
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        recipient_phone = request.POST.get('phone')

        # 2.进行校验
        if not all([recipient_name, recipient_addr, zip_code, recipient_phone]):
            return render(request, 'users/user_center_site.html', {'errmsg': '参数不能为空!'})

        # 3.添加收货地址
        Address.objects.add_one_address(passport_id=passport_id,
                                        recipient_name=recipient_name,
                                        recipient_addr=recipient_addr,
                                        zip_code=zip_code,
                                        recipient_phone=recipient_phone)

        # 4.返回应答

Book/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}图灵书城书城-登录{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 通过id获取用户名和密码
            var username = $('#username').val()
            var password = $('#pwd').val()
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            {# prop方法用于检索或设置属性的值 #}
            var remember = $('input[name="remember"]').prop('checked')
            var verifycode = $('input[name="vc"]').val()
            // 发起ajax请求
            var params = {
                'username': username,
                'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode': verifycode,
            }
            {# post提交前端数据 #}
            $.post('/user/login/', params, function (data) {
                // 用户名密码错误 {'res':0}
              	//验证码错误{'res':1}
                // 登录成功 {'res':2}
                if (data.res == 0){
                    $('#username').next().html('用户名或密码错误').show()
                }
              	else if(data.res==1){
                    $('#username').next().html('验证码错误').show()
                }
                else
                {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
        <a href="{% url 'books:index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">图灵书城</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    {% csrf_token %}
                    <input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" id="pwd" class="pass_input" value="{{ password }}" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名和密码</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <div style="top: 100px; position: absolute;">
                        <input type="text" id="vc" name="vc">
                        <img id='verifycode' src="/user/verifycode/" onclick="this.src='/user/verifycode/?'+Math.random()" alt="CheckCode"/>
                    </div>
                    <input type="button" id="btnLogin" value="登录" class="input_submit">
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
{% block cart_count %}{% endblock cart_count %}

Book/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}图灵书城-用户中心{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
                <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                        <ul class="user_info_list">
                            <li><span>用户名：</span>{{ request.session.username }}</li>
                            {% if addr %}
                                <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
                                <li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无</li>
                                <li><span>联系地址：</span>无</li>
                            {% endif %}
                        </ul>
                </div>
                
                <h3 class="common_title2">最近浏览</h3>
                <div class="has_view_list">
                    <ul class="book_type_list clearfix">
                        {% for books in books_li %}
                            <li>
                                <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image.url %}"></a>
                                <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ books.price }}</span>
                                    <span class="unit">册</span>
                                    <a href="#" class="add_books" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
    </div>
{% endblock body %}

Book/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}图灵书城-个人中心{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <div class="main_con clearfix">
        {% csrf_token %}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
                {% csrf_token %}
                <h3 class="common_title2">全部订单</h3>
                {# OrderInfo #}
                {% for order in order_li %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">{{ order.status | order_status }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {# 遍历出来的order_books是一个OrderGoods对象 #}
                                {% for order_books in order.order_books_li %}
                                <ul class="order_book_list clearfix">
                                    {# 外键查询，子表查询主表 #}
                                    <li class="col01"><img src="{% static order_books.books.image.url %}"></li>
                                    <li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/册</em></li>
                                    <li class="col03">{{ order_books.count }}</li>
                                    <li class="col04">{{ order_books.amount }}元</li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.total_price }}元</td>
                            <td width="15%">{{ order.status | order_status}}</td>
                            <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">
                                {% ifequal order.status 1 %}去付款{% else %}查看物流{% endifequal %}</a></td>
                        </tr>
                    </tbody>
                </table>
                {% endfor %}

                <div class="pagenation">
                    {% if order_li.has_previous %}
                        <a href="{% url 'user:order' page=order_li.previous_page_number %}">上一页</a>
                    {% endif %}
                    {% for page in pages %}
                        {% if page == order_li.number %}
                            <a href="{% url 'user:order' page=page %}" class="active">{{ page }}</a>
                        {% else %}
                            <a href="{% url 'user:order' page=page %}">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if order_li.has_next %}
                        <a href="{% url 'user:order' page=order_li.next_page_number %}">下一页</a>
                    {% endif %}
                </div>
        </div>
    </div>
{% endblock body %}
{% block bottomfiles%}
    <script>
    $(function () {
        $('.oper_btn').click(function () {
            // 获取订单id和订单的状态
            var order_id = $(this).attr('order_id')
            var order_status = $(this).attr('order_status')
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            var params = {
                'order_id':order_id,
                'csrfmiddlewaretoken':csrf,
                //获取当前网址，便于支付成功后跳转
                'pwd_url':location.href,

            }
            if (order_status == 1){
                $.post('{% url 'order:pay' %}', params, function (data) {
                    if (data.res == 3){
                        // 把用户引导支付页面
                        //window.open(data.pay_url)
                        window.location.href= data.pay_url
                        // 查询用户的支付结果
                        $.post('{% url 'order:check_pay' %}', params, function (data) {
                            if (data.res == 3){
                                alert('支付成功')

                                // 重新刷新页面
                                window.history.back()
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>
{% endblock bottomfiles %}

Book/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
                <h3 class="common_title2">收货地址</h3>
                <div class="site_con">
                    <dl>
                        <dt>当前地址：</dt>
                        {% if addr %}
                            <dd>{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
                        {% else %}
                            <dd>无</dd>
                        {% endif %}
                    </dl>
                    <dl>
                        <dt>所有地址：</dt>
                            {% csrf_token %}
                        {% for a in addrs %}

                            <dd>{{ a.recipient_addr }} （{{ a.recipient_name }} 收） {{ a.recipient_phone }}<a
                                    href="javascript:;" class="default" addr_id="{{ a.id }}"> 设为默认   </a>
                                <a href="javascript:;" class="delete" addr_id="{{ a.id }}"> 删除</a></dd>
                        {% endfor %}
                    </dl>
                </div>
                <h3 class="common_title2">添加地址</h3>
                <div class="site_con">
                    <form method="post" action="/user/address/">
                        {% csrf_token %}
                        <div class="form_group">
                            <label>收件人：</label>
                            <input type="text" name="username">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="addr"></textarea>
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="zip_code">
                        </div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="phone">
                        </div>
                        <input type="submit" value="提交" class="info_submit">
                    </form>
                </div>
        </div>
    </div>

    <script>
    $(function(){
        $('.default').click(function(){
            var addr_id=$(this).attr('addr_id');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params={
                'addr_id':addr_id,
                'csrfmiddlewaretoken':csrf,
            }
            $.post('{% url 'user:default_address' %}',params,function(data){
                if(data.res==1){
                    location.reload()
                }else {
                    alert('设置失败!')
                }
            })
        })

        $('.delete').click(function(){
            var addr_id=$(this).attr('addr_id');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params={
                'addr_id':addr_id,
                'csrfmiddlewaretoken':csrf,
            }
            $.post('{% url 'user:delete_address' %}',params,function(data){
                if(data.res==1){
                    location.reload()
                }else {
                    alert('删除失败!')
                }
            })
        })


    })
    </script>
{% endblock body %}